mkdir apk | move *.apk apk
mkdir comprimidos | move *.zip comprimidos
mkdir comprimidos | move *.rar comprimidos
mkdir exe | move *.exe exe
mkdir dwgAutocad | move *.dwg dwgAutocad
mkdir epsYpng | move *.eps epsYpng
mkdir epsYpng | move *.png epsYpng
mkdir gif | move *.gif gif
mkdir Imagenes | move *.jpeg Imagenes
mkdir Imagenes | move *.jpg Imagenes
mkdir Imagenes | move *.svg Imagenes
mkdir MatlabScriptFunction | move *.m MatlabScriptFunction
mkdir MatlabScriptFunction | move *.mat MatlabScriptFunction
mkdir mp3 | move *.mp3 mp3
mkdir office | move *.xls office
mkdir office | move *.doc office
mkdir office | move *.ppt office
mkdir office | move *.pps office
mkdir office | move *.pub office
mkdir pdf | move *.pdf pdf
mkdir solidosFormatosVarios | move *.step solidosFormatosVarios
mkdir solidosFormatosVarios | move *.stp solidosFormatosVarios
mkdir SolidWorksParts | move *.sldprt SolidWorksParts
mkdir SolidWorksParts | move *.sldasm SolidWorksParts
mkdir SolidWorksParts | move *.slddrw SolidWorksParts
mkdir SolidWorksParts | move *.slddrt SolidWorksParts
mkdir txtYcsv | move *.txt txtYcsv
mkdir txtYcsv | move *.csv txtYcsv