mkdir apk | mv *.apk apk
mkdir comprimidos | mv *.zip comprimidos
mkdir comprimidos | mv *.rar comprimidos
mkdir exe | mv *.exe exe
mkdir dwgAutocad | mv *.dwg dwgAutocad
mkdir epsYpng | mv *.eps epsYpng
mkdir epsYpng | mv *.png epsYpng
mkdir gif | mv *.gif gif
mkdir Imagenes | mv *.jpeg Imagenes
mkdir Imagenes | mv *.jpg Imagenes
mkdir Imagenes | mv *.svg Imagenes
mkdir MatlabScriptFunction | mv *.m MatlabScriptFunction
mkdir MatlabScriptFunction | mv *.mat MatlabScriptFunction
mkdir mp3 | mv *.mp3 mp3
mkdir office | mv *.xls office
mkdir office | mv *.doc office
mkdir office | mv *.ppt office
mkdir office | mv *.pps office
mkdir office | mv *.pub office
mkdir pdf | mv *.pdf pdf
mkdir solidosFormatosVarios | mv *.step solidosFormatosVarios
mkdir solidosFormatosVarios | mv *.stp solidosFormatosVarios
mkdir SolidWorksParts | mv *.sldprt SolidWorksParts
mkdir SolidWorksParts | mv *.sldasm SolidWorksParts
mkdir SolidWorksParts | mv *.slddrw SolidWorksParts
mkdir SolidWorksParts | mv *.slddrt SolidWorksParts
mkdir txtYcsv | mv *.txt txtYcsv
mkdir txtYcsv | mv *.csv txtYcsv